version: "3.8"

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - mongo
    mem_limit: 1g
    cpus: 1
    restart: always
    env_file:
      - .env

  user:
    build:
      context: .
      dockerfile: Dockerfile.user
    ports:
      - "5001:5001"
    networks:
      - app-network
    depends_on:
      - mongo
    env_file:
      - .env
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
