# Chọn image Node.js cơ sở
FROM node:18-alpine

# Thiết lập thư mục làm việc trong container
WORKDIR /usr/src/app

# Copy package.json và cài đặt dependencies
COPY frontend/package*.json ./
RUN npm install --production

# Copy mã nguồn của User
COPY ./frontend ./frontend

# Expose port mà User service lắng nghe
EXPOSE 5001

# Lệnh khởi động khi container bắt đầu chạy
CMD ["node", "frontend/index.js"]
