version: "3.8"
services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile.api # Chỉ định Dockerfile cho API
    ports:
      - "5000:5000" # Map port 3000 của container sang port 3000 của máy host
    networks:
      - app-network
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/fashionstock
    mem_limit: 1g
    cpus: 1
    restart: always

  user:
    build:
      context: .
      dockerfile: Dockerfile.user # Chỉ định Dockerfile cho User
    ports:
      - "5001:5001" # Map port 3001 của container sang port 3001 của máy host
    networks:
      - app-network
    depends_on:
      - mongo
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
