# Build stage
FROM node:18-alpine as builder
WORKDIR /usr/src/app

# Copy package.json -> cài dependencies
COPY frontend/package*.json ./
RUN npm install

# Copy toàn bộ code React
COPY ./frontend ./frontend
WORKDIR /usr/src/app/frontend

# Build ứng dụng
RUN npm run build

EXPOSE 5001
