name: CI – Build Docker Image

on:
  push:
    branches:
      - main        # hoặc branch bạn muốn theo dõi
      - release/*
  workflow_dispatch:  # cho phép chạy thủ công từ giao diện GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout mã nguồn
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Thiết lập Docker Buildx (nếu bạn cần multi-platform)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3. (Tuỳ chọn) Đăng nhập nếu bạn muốn push image lên Docker Hub/GitHub Packages
    #- name: Log in to registry
    #  uses: docker/login-action@v2
    #  with:
    #    registry: docker.io
    #    username: ${{ secrets.DOCKERHUB_USERNAME }}
    #    password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 4. Build Docker image
    - name: Build and tag Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.api        # hoặc Dockerfile ở root nếu bạn gộp cả API/FE
        push: false                   # nếu không push thì để false
        tags: |
          stock-fashion-api:latest

    # 5. (Tuỳ chọn) Build tiếp Frontend nếu cần
    - name: Build and tag Frontend image
      uses: docker/build-push-action@v4  
      with:
       context: .
       file: ./Dockerfile.user
       push: false
       tags: stock-fashion-frontend:latest

    # 5. (Tuỳ chọn) Push image lên registry
    #- name: Push to Docker Hub
    #  uses: docker/build-push-action@v4
    #  with:
    #    context: .
    #    file: ./Dockerfile.api
    #    push: true
    #    tags: yourdockerhubuser/stock-fashion-api:latest
